  `signature_type` enum('zakljucavanje','odobrenje','potvrda') DEFAULT 'zakljucavanje',
  `note` text,
  `reason_code` varchar(64) NOT NULL,
  `reason_description` varchar(255) DEFAULT NULL,
  `record_hash` varchar(128) NOT NULL,
  `record_version` int NOT NULL DEFAULT '1',
  `server_timezone` varchar(64) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `device_info` varchar(255) DEFAULT NULL,
  `session_id` varchar(64) DEFAULT NULL,
  `revision_no` int DEFAULT '1',
  `mfa_challenge` varchar(128) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
