using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace YasGMP.Models
{
    /// <summary>
    /// Represents an API key used to authenticate API requests with full audit metadata.
    /// </summary>
    public partial class ApiKey
    {
        /// <summary>Primary key of the API key record.</summary>
        [Key]
        public int Id { get; set; }

        /// <summary>The API key value (secret).</summary>
        [Required]
        [MaxLength(255)]
        public string Key { get; set; } = string.Empty;

        /// <summary>Description, label, or purpose of the key.</summary>
        [MaxLength(255)]
        public string? Description { get; set; }

        /// <summary>Owner user id (FK to users.id).</summary>
        public int? OwnerId { get; set; }

        /// <summary>Navigation to the owning user.</summary>
        [ForeignKey(nameof(OwnerId))]
        public User? Owner { get; set; }

        /// <summary>Whether the key is active and can be used.</summary>
        public bool IsActive { get; set; } = true;

        /// <summary>Date created (UTC).</summary>
        public DateTime? CreatedAt { get; set; }

        /// <summary>Last time the key was used (UTC).</summary>
        public DateTime? LastUsedAt { get; set; }

        /// <summary>Navigation property for usage logs generated by this API key.</summary>
        public ICollection<ApiUsageLog> UsageLogEntries { get; set; } = new List<ApiUsageLog>();
    }
}

