using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System;

namespace YasGMP.Models
{
    /// <summary>Entity model for the `report_schedule` table.</summary>
    [Table("report_schedule")]
    public class ReportSchedule
    {
        /// <summary>Gets or sets the id.</summary>
        [Key]
        [Column("id")]
        public int Id { get; set; }

        /// <summary>Gets or sets the report name.</summary>
        [Column("report_name")]
        [StringLength(100)]
        public string? ReportName { get; set; }

        /// <summary>Gets or sets the schedule type.</summary>
        [Column("schedule_type")]
        public string? ScheduleType { get; set; }

        /// <summary>Gets or sets the format.</summary>
        [Column("format")]
        public string? Format { get; set; }

        /// <summary>Gets or sets the recipients.</summary>
        [Column("recipients")]
        public string? Recipients { get; set; }

        /// <summary>Gets or sets the last generated.</summary>
        [Column("last_generated")]
        public DateTime? LastGenerated { get; set; }

        /// <summary>Gets or sets the next due.</summary>
        [Column("next_due")]
        public DateTime? NextDue { get; set; }

        /// <summary>Gets or sets the status.</summary>
        [Column("status")]
        public string? Status { get; set; }

        /// <summary>Gets or sets the generated by.</summary>
        [Column("generated_by")]
        public int? GeneratedBy { get; set; }

        /// <summary>Gets or sets the created at.</summary>
        [Column("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>Gets or sets the updated at.</summary>
        [Column("updated_at")]
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets the generated by navigation.
        /// </summary>
        [ForeignKey(nameof(GeneratedBy))]
        public virtual User? GeneratedByNavigation { get; set; }
    }
}
