name: DB Sync Analyzer

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run analyzer
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          ./scripts/analyze_db_sync.ps1

      - name: Summarize mismatches
        id: summary
        shell: pwsh
        run: |
          $path = "reports/mismatch-matrix.csv"
          if (-not (Test-Path $path)) { Write-Host "No mismatch-matrix.csv"; exit 0 }
          $lines = Get-Content $path
          $count = [Math]::Max(0, ($lines.Length - 1))
          "mismatch_count=$count" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
          Write-Host "Mismatches: $count"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: db-sync-reports
          path: |
            reports/**
          if-no-files-found: warn

      - name: Fail on mismatches > 0
        if: steps.summary.outputs.mismatch_count && steps.summary.outputs.mismatch_count != '0'
        run: |
          echo "Database/code mismatches found: ${MISMATCH_COUNT}" && exit 1
        env:
          MISMATCH_COUNT: ${{ steps.summary.outputs.mismatch_count }}

