name: Schema Snapshot Refresher

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit updated schema.json back to repo"
        required: false
        default: "true"
        type: boolean
  schedule:
    - cron: "17 3 * * *"  # daily at 03:17 UTC
  push:
    branches:
      - main
      - master

permissions:
  contents: write

concurrency:
  group: schema-snapshot
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      MYSQL_CS: ${{ secrets.MYSQL_CS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Guard: require MYSQL_CS secret
        if: ${{ env.MYSQL_CS == '' || env.MYSQL_CS == null }}
        run: |
          echo "MYSQL_CS secret is not set; skipping snapshot." && exit 0

      - name: Run snapshot tool
        run: |
          dotnet run --project tools/SchemaSnapshot/SchemaSnapshot.csproj -c Release

      - name: Run analyzer after snapshot
        shell: pwsh
        run: |
          ./scripts/analyze_db_sync.ps1

      - name: Summarize mismatches
        id: summary
        shell: pwsh
        run: |
          $path = "reports/mismatch-matrix.csv"
          if (-not (Test-Path $path)) { "mismatch_count=0" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append; exit 0 }
          $lines = Get-Content $path
          $count = [Math]::Max(0, ($lines.Length - 1))
          "mismatch_count=$count" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
          Write-Host "Mismatches: $count"

      - name: Detect changes
        id: diff
        shell: bash
        run: |
          git add tools/schema/snapshots/schema.json
          if git diff --cached --quiet -- tools/schema/snapshots/schema.json; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push snapshot
        if: >-
          ${{ steps.diff.outputs.changed == 'true' &&
              (github.event_name == 'workflow_dispatch' && inputs.commit == true ||
               vars.ALLOW_SCHEMA_SNAPSHOT_COMMIT == 'true') }}
        shell: bash
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "ci: refresh schema snapshot"
          git push

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema-and-reports
          path: |
            tools/schema/snapshots/schema.json
            reports/**
          if-no-files-found: error

      - name: Fail on mismatches > 0
        if: steps.summary.outputs.mismatch_count && steps.summary.outputs.mismatch_count != '0'
        run: |
          echo "Analyzer found mismatches: ${{ steps.summary.outputs.mismatch_count }}" && exit 1
