// File: Models/ApiKey.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace YasGMP.Models
{
    /// <summary>
    /// Represents an API key used to authenticate API requests.
    /// </summary>
    public class ApiKey
    {
        /// <summary>
        /// Primary key of the API key record.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// The API key value (secret).
        /// </summary>
        [Required]
        public string Key { get; set; } = string.Empty;

        /// <summary>
        /// Owner (user, service, or application) of this API key.
        /// </summary>
        [Required]
        public string Owner { get; set; } = string.Empty;

        /// <summary>
        /// Whether the key is active and can be used.
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Navigation property for usage logs generated by this API key.
        /// </summary>
        public ICollection<ApiUsageLog> UsageLogs { get; set; } = new List<ApiUsageLog>();
    }
}
