// File: Models/ApiKey.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace YasGMP.Models
{
    /// <summary>
    /// Represents an API key used to authenticate API requests.
    /// </summary>
    public class ApiKey
    {
        /// <summary>
        /// Primary key of the API key record.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// The API key value (secret).
        /// </summary>
        [Required]
        [System.ComponentModel.DataAnnotations.Schema.Column("key_value")]
        public string Key { get; set; } = string.Empty;

        /// <summary>
        /// Owner user id (FK to users.id).
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column("owner_id")]
        public int? OwnerId { get; set; }

        /// <summary>Description, label, or purpose of the key.</summary>
        [System.ComponentModel.DataAnnotations.Schema.Column("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Whether the key is active and can be used.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column("is_active")]
        public bool IsActive { get; set; } = true;

        /// <summary>Date created (UTC).</summary>
        [System.ComponentModel.DataAnnotations.Schema.Column("created_at")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>Last time the key was used (UTC).</summary>
        [System.ComponentModel.DataAnnotations.Schema.Column("last_used_at")]
        public System.DateTime? LastUsedAt { get; set; }

        /// <summary>
        /// Navigation property for usage logs generated by this API key.
        /// </summary>
        public ICollection<ApiUsageLog> UsageLogs { get; set; } = new List<ApiUsageLog>();
    }
}
